09-02 solutions + fixed some tests
js-tasks-ru/nodejs-20210618_daniil-rabizo pull request #11
Opened 2021-07-31 09:51 UTC by dnlrbz

2021-07-31 09:52 UTC, jsru commented
Добавляю преподавателя (@tadjik1) для код-ревью.

2021-07-31 09:53 UTC, dnlrbz commented on 09-email/02-order/test/orders.test.js
> +        expect(get(envelope, 'to[0]'), 'письмо отправлено на почту пользователя').to
вот тут пришлось эту строку сюда переместить, потому что мы ожидаем асинхронный event envelope

2021-07-31 09:54 UTC, dnlrbz commented
@tadjik1 просьба судить код строго)))

2021-08-06 18:30 UTC, dnlrbz commented
@tadjik1 конфликт, потому что я случайно нажал "посмотреть решение преподавателя" и оно смерджилось в мастер. Можете пожалуйста ревертнуть этот коммит, или просто сделать мне ревью на мой код)

2021-08-14 08:36 UTC, tadjik1 commented on 09-email/02-order/controllers/orders.js
> +    console.error(e);
это очень плохо) вы просто логируете ошибку и больше ничего с ней не делаете - значит сервер ответит статусом 404 и пользователь не поймет что именно пошло не так

2021-08-14 08:38 UTC, tadjik1 requested changes
@dnlrbz в целом все отлично, мне не понравился только один небольшой момент при отправке почты. почему вы именно так обработали ошибку, какая была идея?

2021-08-14 09:07 UTC, dnlrbz commented on 09-email/02-order/controllers/orders.js
> +    console.error(e);
спасибо, исправил, возращаю теперь 400 здесь и body с ошибкой

2021-08-14 09:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @tadjik1

2021-08-14 09:19 UTC, tadjik1 commented on 09-email/02-order/controllers/orders.js
> +    console.error(e);
хорошо :)

2021-08-14 09:19 UTC, tadjik1 approved these changes
👍

2021-08-14 09:20 UTC, merged